<?php
// module/Album/view/album/album/add.phtml:

$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<div class="control-group">
	<?php $title = $form->get('title');?>
	<?php echo $this->formLabel($title); ?> 
	<div class="controls">
			<?php echo $this->formInput($title);?>
	</div>
</div>
<div class="control-group">
	<?php $artist = $form->get('artist'); ?>
	<?php echo $this->formLabel($artist);?>
	<div class="controls">
			<?php echo $this->formInput($artist); ?>
	</div>
</div>
<div class="control-group">
	<div class="controls">
		<?php echo $this->formSubmit($form->get('submit')); ?>
	</div>
</div>
<?php echo $this->form()->closeTag(); ?>